### ISSUE TITLE
Output 0-359?

### ISSUE THREAD

**Issue by Tobbera** [RobTillaart/runningAngle#15] opened 2023-02-16 08:11 UTC
Happy I found this library. It makes the averaging of the compass for my autopilot much easier than working with kalman filters etc manually in the code.

Question:
I input a 0-359.99 degree value to the filter and would like to have the same range back from the filter. But the filter gives me  -180-180. Is the following math the correct way to make this happen?

` if (smoothed_heading < 0) smoothed_heading += 360;`

Thanks in advance.

**Comment by RobTillaart** [comment] 2023-02-16 08:19
Thanks for the question.

Your code seems correct to me. It maps -1. To 359 etc.

The way to verify is to write a sketch that adds one angle and the same angle should be returned.
Then loop from 0 to 359.99 and test them all.

Rob

**Comment by Tobbera** [comment] 2023-02-16 08:35
Thank you for that. Seems to work very well!

**Comment by RobTillaart** [comment] 2023-02-16 09:13
test sketch
```cpp
//
//    FILE: runningAngle_0_360.ino
//  AUTHOR: Rob Tillaart
// PURPOSE: demo mapping average from -180..180 to 0..360

#include "runningAngle.h"

uint32_t start, stop;

runningAngle heading(runningAngle::DEGREES);

void setup()
{
  Serial.begin(115200);
  Serial.println(__FILE__);

  start = millis();
  for (int32_t a = 0; a < 36000; a++)
  {
    heading.reset();
    float angle = a * 0.01;
    heading.add(angle);
    float average = heading.getAverage();
    //  map output 0..359.999
    if (average < 0)
    {
      average += 360.0;
    }
    if (abs(angle - average) > 0.0001)
    {
      Serial.print(angle);
      Serial.print("\t");
      Serial.print(average);
      Serial.println();
    }
  }
  stop = millis();
  Serial.println();
  Serial.print("TIME: \t");
  Serial.println(stop - start);
  Serial.println("done...");
}

void loop()
{
}

//  -- END OF FILE --
```

will add it to examples

**Comment by Tobbera** [comment] 2023-02-16 09:23
On a side note: 
Why does it not by default output 0-359? Since its kind if the standard of "degrees", atleast in my world.

**Comment by RobTillaart** [comment] 2023-02-16 09:37
Do not recall the exact reason, I think the mathematical symmetry and accuracy was the reason.

- Symmetry: there are as much negative angles as positive ones
- Accuracy: there are more floats between -1 and 1 than between 179 and 181 

The latter will only be visible when using a lot of decimals.

It might be an idea to set the "midpoint",  so you could also easily map to -90 ..270 or so.  (midpoint 90)

**Comment by RobTillaart** [comment] 2023-02-16 09:59
@Tobbera 
If the issue is solved you may close it.

**Closed as completed by RobTillaart** 2023-02-16 09:59 UTC
Labels: question

**Comment by RobTillaart** [comment] 2023-02-16 12:40
@Tobbera 
Thanks for the support!

**Comment by RobTillaart** [comment] 2023-02-16 12:57
Created a develop branch to support the **midPoint** shifting.
If you have time please give it a try   
added an example too

https://github.com/RobTillaart/runningAngle/tree/develop

I have some ideas for optimizations, but first version should be a straightforward working one.

**Comment by Tobbera** [comment] 2023-02-16 13:00
Looks great! Will try it.

**Comment by edgar-bonet** [comment] 2023-02-16 17:56
The fact that it defaults to [−180,&nbsp;180) is also a matter of coding convenience and efficiency. The core of the algorithm lies in this line:

```c++
_average = wrap(_average + _weight * wrap(angle - _average));
```

In order for the algorithm to produce sensible results, it is absolutely required that the inner `wrap()` function returns a result in an interval centered around zero. The outer `wrap()`, however, is only intended to give a result within a fixed interval, and could well be replaced with a function that wraps to [0,&nbsp;360). Using a single wrap function for both purposes makes the code shorter and simpler.

**Comment by RobTillaart** [comment] 2023-02-16 18:36
Hi Edgar!
Yes, my idea is to keep the internal math using the existing interval -180..180 (stable code) and adjust (last moment) to the interval the user wants.

The develop branch allows any "shift" of interval and it works however every add() call needs to do the shift as it returns the average. Removing the return value e.g. **void add()** removes the math until **getAverage()** is called. Keeping performance by means of a breaking change.

Having only two intervals to choose from makes the code less complex than supporting any range. That is the path I intend to explore (probably tomorrow).
